version: 2.1

executors:
  docker:
    docker:
    - image: circleci/openjdk:11-jdk
      auth:
        username: $OVO_DOCKERHUB_USER
        password: $OVO_DOCKERHUB_PASSWORD
    environment:
      JAVA_OPTS: "-Xmx1g -XX:MaxMetaspaceSize=1g -XX:MetaspaceSize=1g -XX:+CMSClassUnloadingEnabled"
      DEFAULT_AWS_REGION: "eu-west-1"
      AWS_REGION: "eu-west-1"

  machine:
    machine:
      enabled: true
      image: circleci/classic:edge

    environment:
      JAVA_OPTS: "-Xmx1g -XX:MaxMetaspaceSize=1g -XX:MetaspaceSize=1g -XX:+CMSClassUnloadingEnabled"
      DEFAULT_AWS_REGION: "eu-west-1"
      AWS_REGION: "eu-west-1"

commands:
  generate_sbt_cache_key:
    description: "Generate sbt cache key"
    steps:
      - run: md5sum project/build.properties project/plugins.sbt build.sbt > .sbt_cache_key

  store_sbt_cache:
    description: "Store sbt cache"
    steps:
    - generate_sbt_cache_key
    - save_cache:
        key: dependencies-{{ checksum ".sbt_cache_key" }}
        paths:
        - /home/circleci/.ivy2
        - /home/circleci/.sbt
        - /home/circleci/.cache

  restore_sbt_cache:
    description: "Restore sbt cache"
    steps:
    - generate_sbt_cache_key
    - restore_cache:
        keys:
        - dependencies-{{ checksum ".sbt_cache_key" }}
        - dependencies

  add_github_host_ssh_key:
    description: "Add the github host SSH key"
    steps:
    - run:
        name: Adding the github host SSH key
        command: |
          echo 'Adding the github host SSH key...'
          mkdir -p -m 0700 ~/.ssh/
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  configure_git_credentials:
    description: "Configure git credentials"
    steps:
    - run:
        name: Configure git credentials
        command: |
          git config user.name ovo-comms-circleci
          git config user.email "hello.comms@ovoenergy.com"     

jobs:
  build:

    executor: docker

    steps:

    - checkout

    - run: docker login --username $OVO_DOCKERHUB_USER --password $OVO_DOCKERHUB_PASSWORD

    - restore_sbt_cache

    - run: sbt update

    - store_sbt_cache

    - run: sbt headerCheck
    - run: sbt scalafmtCheckAll
    # TODO Make sure scalafmtCheckAll checks it as well
    - run: sbt it:scalafmtCheck
    
    - run: sbt +test:compile

    - persist_to_workspace:
        root: .
        paths:
        - project/target
        - project/project/target
        - target
        - modules/auth/target
        - modules/common/target
        - modules/dynamodb/target
        - modules/s3/target

  s3_unit_test:    
    executor: docker
    steps:
    - checkout
    - run: docker login --username $OVO_DOCKERHUB_USER --password $OVO_DOCKERHUB_PASSWORD
    - restore_sbt_cache
    - attach_workspace:
        at: .

    - run: sbt +s3/test

    - store_test_results:
        path: modules/s3/target/test-reports
        
    - store_artifacts:
        path: target/unit-test.log
        destination: logs/unit-test.log

  auth_unit_test:

    executor: docker

    steps:

    - checkout
    - run: docker login --username $OVO_DOCKERHUB_USER --password $OVO_DOCKERHUB_PASSWORD
    - restore_sbt_cache
    - attach_workspace:
        at: .

    - run: sbt +auth/test

    - store_test_results:
        path: modules/auth/target/test-reports
        
    - store_artifacts:
        path: target/unit-test.log
        destination: logs/unit-test.log

  common_unit_test:

    executor: docker

    steps:

    - checkout
    - run: docker login --username $OVO_DOCKERHUB_USER --password $OVO_DOCKERHUB_PASSWORD
    - restore_sbt_cache
    - attach_workspace:
        at: .

    - run: sbt +common/test

    - store_test_results:
        path: modules/common/target/test-reports
        
    - store_artifacts:
        path: target/unit-test.log
        destination: logs/unit-test.log

  common_integration_test:

    executor: docker

    steps:

    - checkout
    - run: docker login --username $OVO_DOCKERHUB_USER --password $OVO_DOCKERHUB_PASSWORD
    - restore_sbt_cache
    - attach_workspace:
        at: .

    - run: sbt +common/it:test

    - store_test_results:
        path: modules/common/target/test-reports

    - store_artifacts:
        path: target/it-test.log
        destination: logs/it-test.log

  auth_integration_test:

    executor: docker

    steps:

    - checkout
    - run: docker login --username $OVO_DOCKERHUB_USER --password $OVO_DOCKERHUB_PASSWORD
    - restore_sbt_cache
    - attach_workspace:
        at: .

    - run: sbt +auth/it:test

    - store_test_results:
        path: modules/auth/target/test-reports

    - store_artifacts:
        path: target/it-test.log
        destination: logs/it-test.log

  s3_integration_test:

    executor: docker

    steps:

    - checkout
    - run: docker login --username $OVO_DOCKERHUB_USER --password $OVO_DOCKERHUB_PASSWORD
    - restore_sbt_cache
    - attach_workspace:
        at: .

    - run: sbt +s3/it:test

    - store_test_results:
        path: modules/s3/target/test-reports

    - store_artifacts:
        path: target/it-test.log
        destination: logs/it-test.log

  tag:

    executor: docker

    steps:
    - checkout
    - run: docker login --username $OVO_DOCKERHUB_USER --password $OVO_DOCKERHUB_PASSWORD
    - attach_workspace:
        at: .
    - add_github_host_ssh_key
    - configure_git_credentials
    - run: build/tag.sh
    # Update the workspace to make sure the git tags are available to the
    # downstream jobs
    - persist_to_workspace:
        root: .
        paths:
        - .git

  release:

    executor: docker

    steps:
    - checkout
    - run: docker login --username $OVO_DOCKERHUB_USER --password $OVO_DOCKERHUB_PASSWORD
    - attach_workspace:
        at: .
    - restore_sbt_cache
    - run:
        command: sbt +releaseEarly
        no_output_timeout: 20m

workflows:

  main:
    jobs:
    - build:
        context: ovo-internal-public

    - auth_unit_test:
        context: ovo-internal-public
        requires:
        - build

    - common_unit_test:
        context: ovo-internal-public
        requires:
        - build
    
    - s3_unit_test:
        context: ovo-internal-public
        requires:
        - build

    - auth_integration_test:
        context: ovo-internal-public
        requires:
        - build

    - common_integration_test:
        context: ovo-internal-public
        requires:
        - build
    
    - s3_integration_test:
        context: ovo-internal-public
        requires:
        - build

    - tag:
        context: ovo-internal-public
        requires:
        - build
        - auth_unit_test
        - common_unit_test
        - s3_unit_test
        - auth_integration_test
        - common_integration_test
        - s3_integration_test
        filters:
          branches:
            only: master

    - release:
        context: ovo-internal-public
        requires:
        - tag


